#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-robumeta
Version  : 2.0
Release  : 2
URL      : https://cran.r-project.org/src/contrib/robumeta_2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/robumeta_2.0.tar.gz
Summary  : Robust Variance Meta-Regression
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-R
BuildRequires : util-linux

%description
No detailed description available

%prep
%setup -q -c -n robumeta

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571874461

%install
export SOURCE_DATE_EPOCH=1571874461
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library robumeta
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library robumeta
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library robumeta
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc robumeta || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/robumeta/DESCRIPTION
/usr/lib64/R/library/robumeta/INDEX
/usr/lib64/R/library/robumeta/Meta/Rd.rds
/usr/lib64/R/library/robumeta/Meta/data.rds
/usr/lib64/R/library/robumeta/Meta/features.rds
/usr/lib64/R/library/robumeta/Meta/hsearch.rds
/usr/lib64/R/library/robumeta/Meta/links.rds
/usr/lib64/R/library/robumeta/Meta/nsInfo.rds
/usr/lib64/R/library/robumeta/Meta/package.rds
/usr/lib64/R/library/robumeta/Meta/vignette.rds
/usr/lib64/R/library/robumeta/NAMESPACE
/usr/lib64/R/library/robumeta/R/robumeta
/usr/lib64/R/library/robumeta/R/robumeta.rdb
/usr/lib64/R/library/robumeta/R/robumeta.rdx
/usr/lib64/R/library/robumeta/data/Rdata.rdb
/usr/lib64/R/library/robumeta/data/Rdata.rds
/usr/lib64/R/library/robumeta/data/Rdata.rdx
/usr/lib64/R/library/robumeta/doc/index.html
/usr/lib64/R/library/robumeta/doc/robumetaVignette.pdf
/usr/lib64/R/library/robumeta/doc/robumetaVignette.pdf.asis
/usr/lib64/R/library/robumeta/help/AnIndex
/usr/lib64/R/library/robumeta/help/aliases.rds
/usr/lib64/R/library/robumeta/help/paths.rds
/usr/lib64/R/library/robumeta/help/robumeta.rdb
/usr/lib64/R/library/robumeta/help/robumeta.rdx
/usr/lib64/R/library/robumeta/html/00Index.html
/usr/lib64/R/library/robumeta/html/R.css
/usr/lib64/R/library/robumeta/tests/testthat/testCorrelated.R
/usr/lib64/R/library/robumeta/tests/testthat/testHierarchical.R
/usr/lib64/R/library/robumeta/tests/testthat/testUserWeights.R
